# 5CS037 - Concepts and Technologies of AI.
# Worksheet - 1: A coding exercises on Numpy.

### Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initializing an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

# 2. Initializing an all-ones array with size 4x2
ones_array = np.ones((4, 2))
print("\nOnes Array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_array = np.full((3, 3), 7)  # Shape 3x3, filled with 7
print("\nFilled Array:\n", fill_array)

# 4. Return a new array of zeros with the same shape as a given array
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Like Array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape as a given array
ones_like_array = np.ones_like(given_array)
print("\nOnes Like Array:\n", ones_like_array)

# 6. Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)


Empty Array:
 [[4.97742726e-310 0.00000000e+000]
 [1.07809766e-004 6.56040915e-310]]

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
 [[0 0]
 [0 0]]

Ones Like Array:
 [[1 1]
 [1 1]]

Converted NumPy Array:
 [1 2 3 4]


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("Array with values 10 to 49:\n", range_array)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nMean of Random Array:\n", mean_value)

# 5. Create a 10x10 array with random values and find the min and max
random_10x10 = np.random.random((10, 10))
min_value, max_value = random_10x10.min(), random_10x10.max()
print("\nMin and Max of 10x10 Random Array:\n", min_value, max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th Element as 1:\n", zero_array)

# 7. Reverse an array
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Border Array:\n", border_array)

# 9. Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array with values 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of Random Array:
 0.47650556697758295

Min and Max of 10x10 Random Array:
 0.004214687550633256 0.9932877022287291

Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed Array:
 [0, 4, 0, 0, 2, 1]

2D Border Array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
print("Add:\n", x + y)

# 2. Subtract the two arrays
print("\nSubtract:\n", x - y)

# 3. Multiply the array with an integer
print("\nMultiply with 2:\n", x * 2)

# 4. Square each element of the array
print("\nSquare:\n", np.square(x))

# 5. Dot product
print("\nDot Product v.w:\n", np.dot(v, w))
print("Dot Product x.v:\n", np.dot(x, v))
print("Dot Product x.y:\n", np.dot(x, y))

# 6. Concatenate x and y along rows; v and w along columns
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print("\nConcatenated x and y:\n", concat_xy)
print("Concatenated v and w:\n", concat_vw)

# 7. Concatenate x and v; observe error
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\nError Explanation:\n", e)


Add:
 [[ 6  8]
 [10 13]]

Subtract:
 [[-4 -4]
 [-4 -3]]

Multiply with 2:
 [[ 2  4]
 [ 6 10]]

Square:
 [[ 1  4]
 [ 9 25]]

Dot Product v.w:
 219
Dot Product x.v:
 [29 77]
Dot Product x.y:
 [[19 22]
 [50 58]]

Concatenated x and y:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w:
 [[ 9 10]
 [11 12]]

Error Explanation:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


### Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1     
x − y + 2z = −3   
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("\nA.A^-1:\n", identity)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)

# 3. Prove (AB)^T = (B^T)(A^T)
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("\n(AB)^T:\n", AB_T)
print("(B^T)(A^T):\n", BT_AT)

# 4. Solve Linear Equation
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])
solution = np.linalg.solve(coeff_matrix, constants)
print("\nSolution of Linear Equations:\n", solution)



A.A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]
(B^T)(A^T):
 [[23 51]
 [13 29]]

Solution of Linear Equations:
 [ 2.  1. -2.]
